const usersData = [

  
  { id: 0, 
    ProjectName: '111 Main Street, Hattiesburb MS', 
    Processed: 'Completed', 
    Score: '73%', 
    Review: 'Yes',
    Completed: "",
    Schedule: 'sched0002',
    Cost: 'sched00021',
  },
  { id: 1, 
    ProjectName: '111 Main Street, Hattiesburb MS', 
    Processed: 'Completed', 
    Score: '100%', 
    Review: 'Yes',
    Completed: '',
    Schedule: 'sched0002',
    Cost: 'sched00021',
  },
  { id: 2, 
    ProjectName: '111 Main Street, Hattiesburb MS', 
    Processed: 'Completed', 
    Score: '73%', 
    Review: 'Yes',
    Completed: '',
    Schedule: 'sched0002',
    Cost: 'sched00021',
  },
  { id: 3, 
    ProjectName: '111 Main Street, Hattiesburb MS', 
    Processed: 'Completed', 
    Score: '100%', 
    Review: 'Yes',
    Completed: '',
    Schedule: 'sched0002',
    Cost: 'sched00021',
  },
]

export default usersData
