export default {
    REGISTER: '/auth/user/authanticate',
    VERIFY_OTP: '/auth/verify-otp',
    RESEND_OTP: 'auth/resend-otp',
    FORGOT_PASSWORD: 'auth/forgot-password/send-otp',
    RESET_PASSWORD: 'auth/forgot-password/set-new-password',
    GET_USER_INFO: '/me',
    GET_SPECILISATIONS: '/specialties',
    GET_SUB_SPECILISATIONS_BY_SPECIALITYID: '/specialties/sub-specialties/by-speciality',
    ADD_BASIC_DETAILS: '/doctors/doctor-basic-details',
    ADD_COMPLETE_DETAILS: '/doctors/doctor-complete-details',
    ADD_PATIENT: '/doctors/prescriptions',
    ADD_PRESCRIPTION: '/doctors/prescriptions',
    GET_APPOINTMENTS: '/appointments/users',
    SHARED_REPORTS: '/share/with-me',
    GET_PATIENTS: '/doctors/my-patients',
    UPLOAD_RAW_FILE: '/doctors/upload-doctor-complete-details-files',
    UPLOAD_AVATAR: '/auth/upload-avatar',
    LOGIN: '/admin/login',
    GET_DOCTORS_LIST: '/doctors',
    GET_PATIENTS_LIST: '/patient',
    GET_BLOGS_LIST: '/admin/blogs',
    GET_INTERESTS_LIST: '/admin/blogs/interests',
    // DELETE_INTERESTS_LIST: '/admin/blogs/interests/:id'
};
